spring.application.name=APIgateway
server.port=8443
server.ssl.key-store=classpath:sidis-keystore.p12
server.ssl.key-store-password=sidis_g6_3da
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=sidis-key

# Aircraft Service
spring.cloud.gateway.server.webflux.routes[0].id=aircraft-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/hangar/**

# Airport Service
spring.cloud.gateway.server.webflux.routes[1].id=airport-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/airports/**

# Maintenance Service
spring.cloud.gateway.server.webflux.routes[2].id=maintenance-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/maintenance/**

# Route Service
spring.cloud.gateway.server.webflux.routes[3].id=route-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/routes/**