spring.application.name=APIgateway
server.port=7979

# Aircraft Service
spring.cloud.gateway.server.webflux.routes[0].id=aircraft-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/hangar/**

# Airport Service
spring.cloud.gateway.server.webflux.routes[1].id=airport-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/airports/**

# Route Service
spring.cloud.gateway.server.webflux.routes[2].id=route-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/routes/**